Samuel dec27 post
fredhu0514/world-map-album pull request #8
Opened 2023-12-30 01:31 UTC by Samuelzmx

add a new table and post&delete method

2023-12-30 01:32 UTC, Samuelzmx commented
![12251703899512_ pic](https://github.com/fredhu0514/world-map-album/assets/143770255/f6b5fce5-a9a0-49e4-90d5-b627321cc889)
the curl tests for post and delete are passed, the table can successfully add new data and delete data.

2024-01-02 01:27 UTC, fredhu0514 requested changes

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/database/database.js
> +export async function getAllBlogs() {
There is no business scenario for `get all blog post`, isn't it?

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/database/database.js
> +export async function getAllBlogs() {
Instead if you really want a get, you should think about how to get by id.

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/app/api/blog/route.js
> +export const GET = async (req, res) => {
You should do a get by id instead of getting all blogs.

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/app/api/blog/route.js
> +export const POST = async (req, res) => {
Great job! Awesome.

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/app/api/blog/route.js
> +export const DELETE = async (req, res) => {
Looks good!

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/database/blog.js
> +let db = new sqlite3.Database('./myBlog.db', sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE, (err) => {
Why are you still using a new db?

2024-01-02 01:27 UTC, fredhu0514 commented on my-travel-map/src/database/blog.js
> +});
Overall, don't think this file is still needed.

2024-01-03 23:58 UTC, closed without merging